# The Docker image that will be used to build your app
image: asciidoctor/docker-asciidoctor:1.69
pages:
  script:
    - make documentation
    - asciidoctor -b html docs/cmd_cachier.1.adoc --out-file public/index.html
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
