name: GitHub Actions Demo
run-name: Building pages for ${{github.ref}}
on: [push]
jobs:
  Publish-Docs:
    runs-on: ubuntu-latest
    container:
      image: asciidoctor/docker-asciidoctor
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Build docs
        run: make documentation

      - run: mkdir -p public
      - run: cp ./docs/manpages/cmd_cachier.1.html ./public/index.html

      - name: Upload artifact.
        uses: actions/uploads-pages-artifact@v1
        with:
          path: ./public/

      - name: Deploy to GitHub Pages
        uses: action/deploy-pages@v1
