name: GitHub Actions Demo
run-name: Building pages for ${{github.ref}}
on: [push]
jobs:


  Publish-Docs:
    needs: Build-Docs
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27

      - name: Build docs
        run: nix-shell --run "make gh_pages" nix/shells/build-docs/shell.nix

      - run: mkdir -p public
      - run: cp ./docs/manpages/cmd_cachier.1.html ./public/index.html

      - name: Upload to pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public/

      - name: Debug artifact download.
        run: find . -type f -name "*.html"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
        with:
          artifact_name: github-pages


