name: GitHub Actions Demo
run-name: Building pages for ${{github.ref}}
on: [push]
jobs:
  Build-Docs:
    runs-on: ubuntu-latest
    container:
      image: asciidoctor/docker-asciidoctor
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build docs
        run: make gh_pages

      - run: mkdir -p public
      - run: cp ./docs/manpages/cmd_cachier.1.html ./public/index.html

  Publish-Docs:
    runs-on: ubuntu-latest
    steps:
      - name: Upload artifact.
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public/index.html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
